#!/bin/sh /etc/rc.common
# START=99
# STOP=15

# start()
# {
# 	#mqtt_enable = $(uci get glconfig.cloud.enable)
# 	#if [ "$mqtt_enable" = "1" ]; then
# 		/usr/bin/gl_mqtt_cli &
# 	#fi
# }

# stop()
# {
# 	killall -9 gl_mqtt_cli
# }

START=99
USE_PROCD=1

start_service() {
        procd_open_instance "gl_mqtt_cli"
        procd_set_param command "/usr/bin/gl_mqtt_cli"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}


