#!/bin/sh /etc/rc.common
# START=99
# STOP=15

# start()
# {
# 	/usr/bin/gl_udp_server &
# }

# stop()
# {
# 	killall -9 gl_udp_server
# }

START=99
USE_PROCD=1

start_service() {
        procd_open_instance "gl_udp_server"
        procd_set_param command "/usr/bin/gl_udp_server"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}

