#!/bin/sh /etc/rc.common
#
# Copyright (C) 2018 Kyson Lok <kysonlok@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99

USE_PROCD=1

PROC="/usr/bin/ss-server"

append_parm() {
	local section="$1"
	local option="$2"
	local switch="$3"
	local default="$4"
	local _loctmp
	config_get _loctmp "$section" "$option"
	[ -n "$_loctmp" -o -n "$default" ] || return 0
	procd_append_param command "$switch" "${_loctmp:-$default}"
}

start_instance() {
	local enable
	config_get_bool enable $1 enable
	[ "$enable" = 1 ] || return 0

	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command ${PROC}

	append_parm $1 server "-s"
	append_parm $1 server_port "-p"
	append_parm $1 password "-k"
	append_parm $1 encryption "-m"
	procd_close_instance
}

start_service() {
	config_load ss-service
	config_foreach start_instance server
}

service_triggers() {
	procd_add_reload_trigger "ss-service"
}
